CREATE TABLE memes_tables (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    url TEXT NOT NULL,
    upvote_count INTEGER,
    downvote_count INTEGER,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);